gui:
  scrollHeight: 20
  nerdFontsVersion: "3"
  border: rounded
  showCommandLog: true
  theme:
    activeBorderColor:
      - blue
    inactiveBorderColor:
      - black
  portraitMode: auto
  showPanelJumps: false
keybinding:
  universal:
    nextTab: <c-e>
    diffingMenu-alt: <c-a>
    jumpToBlock: ["0", "1", "2", "3", "4"]
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  mainBranches:
    - main
    - master
    - dev
    - development
promptToReturnFromSubprocess: false
notARepository: quit
